/**
 * Финальный composite-ranking для generate-plan (после eligibility-фильтров).
 * Числа и формулы — в shared/planRankTrustShared.ts.
 */

export {
  buildAlignedRankSalt,
  buildRankSalt,
  CANDIDATE_COMPOSITE_NUDGE,
  computeCompositeScore,
  computeEmergingBoost,
  computeExplorationThresholdPct,
  dbScoreContribution,
  dbScoreContributionForRanking,
  explainRankingTail,
  explainRankingTailAdult,
  explorationPickActive,
  EXPLORATION_CANDIDATE_BOOST,
  EXPLORATION_PICK_THRESHOLD_PCT,
  getRankingTailBreakdown,
  type RankingTailInput,
  isCandidateTrustForV33,
  isCandidateTrustLevel,
  isEmergingV33,
  isEstablishedTrust,
  isExplorationActive,
  isPoolTrustEligible,
  rankJitter,
  rankJitterFromSeed,
  RANK_JITTER_MAX,
  type RankableRecipeRef,
  type RankingInput,
  type PlanRankingMode,
  type RankingTailBreakdown,
  resolvePlanRankingMode,
  simpleRankSaltHash,
  stableSortPoolForRanking,
  trustOrder,
  trustRankingBonus,
} from "../../../shared/planRankTrustShared.ts";
