// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = "https://hidgiyyunigqazssnydm.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpZGdpeXl1bmlncWF6c3NueWRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg3NTc2NDIsImV4cCI6MjA4NDMzMzY0Mn0.5qGWTbBKjU4TozaS_jguQ-_Fe-B5GOQg_k9g2wXk0AE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false, // Отключаем для мобильных приложений
  },
  global: {
    // Увеличиваем таймаут для мобильных приложений
    fetch: (url, options = {}) => {
      // Увеличиваем таймаут до 60 секунд для мобильных приложений
      const timeout = 60000; // 60 секунд
      
      // Создаём AbortController для отмены запроса при таймауте
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), timeout);
      
      // Добавляем signal к опциям, если его ещё нет
      const fetchOptions = {
        ...options,
        signal: options.signal || controller.signal,
      };
      
      return fetch(url, fetchOptions)
        .then((response) => {
          clearTimeout(timeoutId);
          return response;
        })
        .catch((error) => {
          clearTimeout(timeoutId);
          
          // Улучшаем сообщение об ошибке для мобильных приложений
          if (error.name === 'AbortError' || error.message?.includes('aborted')) {
            throw new Error('Превышено время ожидания ответа от сервера. Проверьте интернет-соединение.');
          }
          if (error.message === 'Failed to fetch' || error.name === 'TypeError') {
            throw new Error('Не удалось подключиться к серверу. Проверьте интернет-соединение.');
          }
          throw error;
        });
    },
  },
});