// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yubgyztjxogoatmjmsgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1Ymd5enRqeG9nb2F0bWptc2dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg3NDcwNjEsImV4cCI6MjA4NDMyMzA2MX0.yq7YbBOkxwdrgT5UC2BWQTP45CMJX4-mfWpqXlcJrq0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});